# http://conda.pydata.org/docs/travis.html
language: python

matrix:
  include:
    - python: 3.4
      env: MINICONDA_PYTHON_VERSION=3.4 SOFT_DEP="mkl mkl-service numexpr matplotlib IPython" CHAN="defaults" INST="pytest-mpl" TEST="--mpl"
    - python: 3.5
      env: MINICONDA_PYTHON_VERSION=3.5 SOFT_DEP="mkl mkl-service numexpr matplotlib IPython" CHAN="defaults" INST="pytest-mpl" TEST="--mpl"
    - python: 3.6
      env: MINICONDA_PYTHON_VERSION=3.6 SOFT_DEP="mkl mkl-service numexpr matplotlib IPython" CHAN="defaults" INST="pytest-mpl" TEST="--mpl"
    - python: 3.6  # => 3.7
      env: MINICONDA_PYTHON_VERSION=3.7 SOFT_DEP="mkl mkl-service numexpr matplotlib IPython" CHAN="defaults" INST="pytest-mpl" TEST="--mpl"
    - python: 3.6  # => 3.6 with conda-forge, without matplotlib
      env: MINICONDA_PYTHON_VERSION=3.6 SOFT_DEP="numexpr IPython" CHAN="conda-forge" INST="" TEST=""
    - python: 3.6  # => 3.6 with without matplotlib, numexpr, IPython
      env: MINICONDA_PYTHON_VERSION=3.6 TRAVIS_PYTHON_VERSION="3.6" SOFT_DEP="" CHAN="defaults" INST="" TEST=""

install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update --all
  # Useful for debugging any issues with conda
  - conda info -a

  # Install and activate environment, install packages
  - conda create -q -n test-environment -c $CHAN python=$MINICONDA_PYTHON_VERSION numpy scipy pytest pytest-cov $SOFT_DEP
  - source activate test-environment
  - pip install coveralls pytest-flake8 $INST
  - python setup.py install
  - cp tests/matplotlibrc .


script: pytest --cov=empymod --flake8 $TEST

after_success: coveralls
